default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test
  url: <%= ENV['DATABASE_URL']%>

production:
  url: <%= ENV['DATABASE_URL']&.sub(/^postgres/, 'postgis') %>
