# Runs our test suite via Github Actions

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:latest
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: './backend'

    # Test setup
    - name: Setup database
      working-directory: './backend'
      env:
        DATABASE_URL: postgis://postgres:postgres@127.0.0.1:5432/backend_test
        RAILS_ENV: test
      run: |
        bundle exec rails db:setup
        bundle exec rails db:migrate
    # Actually run all the tests
    - name: Run tests
      working-directory: './backend'
      env:
        DATABASE_URL: postgis://postgres:postgres@127.0.0.1:5432/backend_test
        RAILS_ENV: test
        CI: true
      run: bundle exec rails test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: './backend'
    # Actually run all the tests
    - name: Run tests
      working-directory: './backend'
      env:
        CI: true
      run: bundle exec rubocop
